### ISSUE TITLE
Evaluate switching graphql server module

### ISSUE THREAD

**Issue by tomeresk** [Soluto/stitch#102]
The [current server](https://github.com/graphql-go/graphql) seems to not be very actively developed, with the last commit being over 5 months ago.
Additionally, when searching for posts/opinions about graphql servers in go, nobody seems to recommend that one, and usually one of two other servers are recommended:

[graphql-go](https://github.com/graph-gophers/graphql-go)
[gqlgen](https://github.com/99designs/gqlgen)

Both options seems pretty good, so we might want to evaluate switching to one of them at some point

**Comment by AvivRubys** [comment]
Both of these servers look like they rely on strong (gqlgen) or somewhat-strong (graph-gophers) typing for resolvers.
Since our schema is dynamic and not known at build time, I'm not sure how we can use either of these solutions - `gqlgen` generates code at compile time, and graph-gophers requires manually writing typesafe resolvers with [no plans to change that](https://github.com/graph-gophers/graphql-go/issues/58)

OTOH, our current server is _very_ flexible which is great for a project like agogos. Unless we have performance/stability/bug issues I don't see the real appeal in switching to something else.

**Comment by AvivRubys** [comment]
Sort-of irrelevant now that it's on apollo
